[package]
name = "cache_browns"
version = "0.1.0"
edition = "2021"
authors = ["Chris Henk <chhenk@microsoft.com>"]

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
flexbuffers = "2.0.0"
uuid = { version = "1.3.3", features = ["v4"] }
